services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identity_db  # This line creates the database
    ports:
      - "5432:5432"
    volumes:
      - pdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pdata:

networks:
  backend:
